# Generated by Django 3.2.16 on 2024-03-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240323_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shopping_cart_recipes',
            field=models.ManyToManyField(blank=True, related_name='recipe_shoppers', to='recipes.Recipe', verbose_name='Рецепты в списке покупок'),
        ),
    ]
